integrations:
  prometheus_remote_write:
    - basic_auth:
        password: ilovesek
        username: ddc
      url: http://167.235.185.121:2053/api/v1/push
  agent:
    enabled: true
    relabel_configs:
      - action: replace
        target_label: instance
        replacement: '{{ NETWORK_NAME }}-{{ NODE_TYPE }}-{{ NODE_ID }}'
      - action: replace
        target_label: job
        replacement: agent-check
    metric_relabel_configs:
      - action: keep
        regex: (prometheus_target_.*|prometheus_sd_discovered_targets|agent_build.*|agent_wal_samples_appended_total|process_start_time_seconds)
        source_labels:
          - __name__
  cadvisor:
    enabled: true
    docker_only: true
    instance: '{{ NETWORK_NAME }}-{{ NODE_TYPE }}-{{ NODE_ID }}'
    relabel_configs:
      - action: replace
        replacement: '{{ NETWORK_NAME }}'
        target_label: job
    metric_relabel_configs:
      - action: keep
        regex: container_cpu_usage_seconds_total|container_fs_limit_bytes|container_fs_usage_bytes|container_last_seen|container_memory_usage_bytes|container_memory_rss|container_network_receive_bytes_total|container_network_transmit_bytes_total|machine_memory_bytes|container_fs_io_time_weighted_seconds_total|container_fs_reads_bytes_total|container_fs_read_seconds_total|container_fs_reads_total|container_fs_writes_bytes_total|container_fs_write_seconds_total|container_fs_writes_total|machine_scrape_error|container_tasks_state|container_network_transmit_packets_total|container_network_transmit_packets_dropped_total|container_network_tcp_usage_total|container_network_transmit_errors_total|container_network_receive_errors_total|container_network_receive_packets_dropped_total|container_network_receive_packets_total
        source_labels:
          - __name__
logs:
  configs:
    - clients:
        - basic_auth:
            password: ilovesek
            username: ddc
          url: http://167.235.185.121:2083/loki/api/v1/push
          external_labels:
            ddc_cluster_id: '{{ CLUSTER_ID }}'
      name: integrations
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: '{{ NETWORK_NAME }}'
          docker_sd_configs:
            - host: unix:///var/run/docker.sock
              refresh_interval: 5s
              filters:
                - name: 'name'
                  values: [ '{{ NODE_TYPE }}-{{ NODE_ID }}', 'nginx' ]
          relabel_configs:
            - action: replace
              replacement: '{{ NETWORK_NAME }}'
              target_label: job
            - action: replace
              replacement: '{{ NETWORK_NAME }}-{{ NODE_TYPE }}-{{ NODE_ID }}'
              target_label: instance
            - source_labels:
                - __meta_docker_container_name
              regex: '/(.*)'
              target_label: container
            - source_labels:
                - __meta_docker_container_log_stream
              target_label: stream
          pipeline_stages:
            - json:
                expressions:
                  http_user_agent:
                  request_uri:
            - drop:
                source: request_uri
                expression: "/(info|health)"
            - drop:
                source: request_uri
                expression: "/activity/*"
metrics:
  configs:
    - name: integrations
      remote_write:
        - basic_auth:
            password: ilovesek
            username: ddc
          url: http://167.235.185.121:2053/api/v1/push
      scrape_configs:
        - job_name: '{{ NETWORK_NAME }}'
          relabel_configs:
            - replacement: '{{ NETWORK_NAME }}-{{ NODE_TYPE }}-{{ NODE_ID }}'
              target_label: instance
            - replacement: '{{ NODE_TYPE }}-{{ NODE_ID }}'
              target_label: container
          static_configs:
            - targets: [ '{{ NODE_TYPE }}-{{ NODE_ID }}:8080' ]
  global:
    scrape_interval: 15s
    external_labels:
      ddc_cluster_id: '{{ CLUSTER_ID }}'
  wal_directory: /tmp/grafana-agent-wal
traces:
  configs:
    - name: integrations
      remote_write:
        - basic_auth:
            password: ilovesek
            username: ddc
          endpoint: 167.235.185.121:2087
          insecure: true
      attributes:
        actions:
          - key: ddc_network
            action: insert
            value: '{{ NETWORK_NAME }}'
          - key: ddc_host
            action: insert
            value: '{{ NETWORK_NAME }}-{{ NODE_TYPE }}-{{ NODE_ID }}'
          - key: ddc_cluster_id
            action: insert
            value: '{{ CLUSTER_ID }}'
      receivers:
        otlp:
          protocols:
            grpc:
