export {
  Box,
  type BoxProps,
  Typography,
  type TypographyProps,
  Button,
  type ButtonProps,
  IconButton,
  type IconButtonProps,
  Table,
  type TableProps,
  TableHead,
  type TableHeadProps,
  TableBody,
  type TableBodyProps,
  TableRow,
  type TableRowProps,
  TableCell,
  type TableCellProps,
  Collapse,
  type CollapseProps,
} from '@mui/material';
